### ISSUE TITLE
autofs::mapOptions?

### ISSUE THREAD

**Issue by TJM** [dhollinger/autofs-puppet#1]
I like the looks of this, simple and works out of the box with minimal dependencies. One suggestion I had was to just make "mapOptions" be an attribute (default {}) on the "init" class so that in YAML its:

```
autofs::mapOptions:
  (the rest)
```

Then you wouldn't need the direct hiera call, you could just pull it in via options?

Just a thought. ;)

~tommy

**Comment by TJM** [comment]
(additional thoughts/reasons)
1. I think it keeps the hiera namespace cleaner and makes it easier to determine what it is for immediately.
2. (which could be solved in the hiera() call), by providing a default {} (empty hash), It would allow me to just install/start autofs, without creating a bunch of local maps (in the event they are in IPA or whatever)

~tommy

**Comment by dhollinger** [comment]
I'll definitely take a look at those changes, though I did just have a baby a couple days ago so it may be a while.

**Comment by dhollinger** [comment]
While good points are raised here, the design of the Module is so that the user only has to create the hiera yaml file and never has to dig into the actual puppet code to get the module to work.

I will, however, be adding code that will allow this module to be used with LDAP/IPA based autofs configuration. Not sure if it will be a parameter or a fact.

**Comment by dhollinger** [comment]
Please see Release 1.1.3 to validate this request has been met.

**Comment by TJM** [comment]
Looks ok to me... I may be missing something, but it looks like `init.pp` still needs:

```
include autofs::mounts
```

right?

**Comment by dhollinger** [comment]
Ok, I've got the convenience module working.

I added a parameter to the main init class:

``` puppet
$mounts
```

It is preset to undef and logic in the init class will check to see if it has content and call the autofs::mounts class, passing the contents of $mount.

There are some problems with this, but it works for now. Working on some re-writes for version 1.2.0

**Comment by TJM** [comment]
You could have just done the include above, if its nil, it won't actually do anything ;)

**Comment by dhollinger** [comment]
Tried that, I get the following error if I don't pass the parameter autofs::mounts:

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Must pass mount to Class[Autofs::Mounts]
```

Seeing as the autofs::mounts class is a convenience class, I would prefer to NOT lock users into using hiera again.

**Comment by TJM** [comment]
Yea, sorry, the $mounts option in mounts.pp would also need `= {}` at the end, and then you would need to define `autofs::mounts::mounts` in hiera, which is just weird, so I like the way you have it instead. :)

**Comment by dhollinger** [comment]
awesome. Closing issue.
