### ISSUE TITLE
Multiple direct mounts

### ISSUE THREAD

**Issue by lpouellet** [dhollinger/autofs-puppet#10]
Hi
Could be me, but it seems that because of concat we cannot have more than one direct map as such 

autofs::mount { 'fixes':
  mount       => '/-',
  mapfile     => '/etc/auto.fixes',
  mapcontents => ['/fixes  -rw,soft,bg,intr,retry=3, nas:/vol/fixes'],
  options     => '--timeout=120',
  order       => 01
  }

autofs::mount { 'cnunix':
  mount       => '/-',
  mapfile     => '/etc/auto.cnunix',
  mapcontents => ['/cnunix -rw,soft,timeo=600,bg,intr,retry=3 nas:/vol/nasp_cnunix'],
  options     => '--timeout=120',
  order       => 02
  }

It yields the following

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Duplicate declaration: Concat::Fragment[autofs::fragment preamble /-] is already declared in file /etc/puppet/environments/KT_ITOPS_Sandbox_ccv_os_rhel7_5/modules/autofs/manifests/mount.pp:48; cannot redeclare at /etc/puppet/environments/KT_ITOPS_Sandbox_ccv_os_rhel7_5/modules/autofs/manifests/mount.pp:48 on node louis-vm.
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

**Comment by dhollinger** [comment]
PR #8 has been merged into master for this purpose. Will be testing it shortly and will be released as part of the 1.3.0 release. It will at least resolve the issue of duplicate declarations.

Issue will remain open until tested and released

**Comment by dhollinger** [comment]
Fixed in 1.3.0
