### ISSUE TITLE
no newline at the end of /etc/auto.master file, with "use_dir" parameter

### ISSUE THREAD

**Issue by jurim76** [dhollinger/autofs-puppet#15]
automount does not recognize chomped "+dir:/etc/auto.master.d
" entry in /etc/auto.master without a new line at the end.

Debian 8
autofs-5.1.1-1
puppetlabs-concat 2.1.0

> puppet agent -t 
> -+dir:/etc/auto.master.d
> ++dir:/etc/auto.master.d
> \ No newline at end of file
> 
> cat /etc/auto.master
> +dir:/etc/auto.master.d
> 
> ls /etc/auto.master.d/
> storage.autofs  tr2.autofs
> 
> automount -f -d -v
> Starting automounter version 5.1.1, master map /etc/auto.master
> using kernel protocol version 5.02
> lookup_nss_read_master: reading master file /etc/auto.master
> parse_init: parse(sun): init gathered global options: (null)
> spawn_mount: mtab link detected, passing -n to mount
> spawn_umount: mtab link detected, passing -n to mount
> no mounts in table
> 
> vi /etc/auto.master
> add a new line
> 
> automount -f -d -v
> ....
> lookup_read_master: lookup(file): read entry /srv/backup
> include_file: lookup(dir): include: /etc/auto.master.d/tr2.autofs
> lookup_nss_read_master: reading master file /etc/auto.master.d/tr2.autofs
> parse_init: parse(sun): init gathered global options: (null)
> lookup_read_master: lookup(file): read entry /srv/tr2
> master_do_mount: mounting /srv/backup
> ....

Fix by me
In mount.pp

  if !defined(Concat[$master]) {
    concat { $master:
      owner  => 'root',
      group  => 'root',
      mode   => '0644',
-->      ensure_newline => true,  <--
      notify => Service[ 'autofs' ],
    }
  }

**Comment by dhollinger** [comment]
Thanks! Fixing that now.

**Comment by dhollinger** [comment]
Added your code to the most recent commit. Thanks!
