### ISSUE TITLE
Duplicate declaration: File[/etc/auto.master.d]  with use_dir = true

### ISSUE THREAD

**Issue by jurim76** [dhollinger/autofs-puppet#16]
## Example hiera yaml 

autofs::mounts:
  tr01:
    mount: '/srv/tr01'
    mapfile: '/etc/auto.tr01'
    mapcontents:
      - 'tr01 -rsize=32768,wsize=32768,noacl test-srv-str-01:/srv/backup/storage'
    options: '--timeout=120'
    order:  01
    use_dir: true
  tr02:
    mount: '/srv/tr02'
    mapfile: '/etc/auto.tr02'
    mapcontents:
      - 'tr02 -rsize=32768,wsize=32768,noacl test-srv-str-02:/srv/backup/storage'
    options: '--timeout=120'
    order:  02
    use_dir: true

> puppet agent -t

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Duplicate declaration: File[/etc/auto.master.d] is already declared in file /srv/puppet/env/production/modules/autofs/manifests/mount.pp:75; cannot redeclare at /srv/puppet/env/production/modules/autofs/manifests/mount.pp:75 on node ld4-bar-dir-01.int.fxservice.com
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

**Comment by dhollinger** [comment]
Definitely a bug. I'll take a look at that and fix ASAP

**Comment by dhollinger** [comment]
Could you test the latest branch with your hiera and let me know if the issue is fixed?
