### ISSUE TITLE
The $ensure parameter to concat::fragment is deprecated

### ISSUE THREAD

**Issue by gocram** [dhollinger/autofs-puppet#17]
when I run the module with any configuration, it returns this warning message for every autofs entry:

```
Warning: Scope(Concat::Fragment[autofs::fragment preamble map directory]): The $ensure parameter to concat::fragment is deprecated and has no effect.
```

In `Concat module` [manual](https://github.com/puppetlabs/puppetlabs-concat), using `ensure` defining `concat::fragment`  is deprecated since  v2.0.0

```
Define: concat::fragment
...
ensure

Deprecated as of concat v2.0.0. Has no effect.
```

**Comment by dhollinger** [comment]
$ensure has been removed from mount.pp

metadata.json updated to require puppetlabs-concat v2.0.0 at minimum.
