### ISSUE TITLE
Service autofs requires package autofs?

### ISSUE THREAD

**Issue by a-dekker** [dhollinger/autofs-puppet#20]
My initial puppet run seems to fail because of an ordering issue.
`Error: /Stage[main]/Autofs::Service/Service[autofs]/ensure: change from stopped to running failed: Could not start Service[autofs]: Execution of '/bin/systemctl start autofs' returned 6: Failed to issue method call: Unit autofs.service failed to load: No such file or directory.`
It tries to start autofs before the packages has been installed.
Does service.pp need to require the package autofs?

**Comment by dhollinger** [comment]
Well, not sure how (in 2 years) I missed that. I'll get it taken care of and released.

Good work @a-dekker!
