### ISSUE TITLE
Add support for +auto_master

### ISSUE THREAD

**Issue by clevelas** [dhollinger/autofs-puppet#27]
For working with ldap mounts and locally defined mounts, I need to add +auto_master to the end of the auto_master file.  I'm not seeing a method to do that.  Something like this I thought might work:

  autofs::mount { 'auto_master':
    mount => '+auto_master',
    order => 999,
  }

But the mount variable is verifying a valid path, so errors out.  I'm thinking an option in the main autofs class?  But that class doesn't really deal with the auto_master file.

So I need an auto.master file that looks like this:

/home /etc/auto.home --timeout=120
+auto_master

**Comment by dhollinger** [comment]
@clevelas This module has been migrated to Vox Pupuli. Please see https://github.com/voxpupuli/puppet-autofs
