### ISSUE TITLE
mount.pp - do you really need to ensure $mount directory?

### ISSUE THREAD

**Issue by sknolin** [dhollinger/autofs-puppet#3]
We use direct maps for mounting, and for this we found we needed to modify mount.pp to not make the directory for us. Doesn't automount always create this directory anyhow?

I didn't do this modification a coworker did, so just sharing it here instead of making a pull request.

Comments show what was removed:

  # autofs does this for us, this freaks out if you use the
  # same mount point twice.
  # example: /filesystem1 /filesystem2 both use /- which is
  # a reserved autofs argument. This creates /-
  #file { $mount:
  #  ensure  => directory,
  #  require => Package[ 'autofs' ],
  #}

  file { $mapfile:
    ensure  => present,
    owner   => 'root',
    group   => 'root',
    mode    => '0644',
    content => template('autofs/auto.map.erb'),
  #  require => File[ $mount ],
    notify  => Service[ 'autofs' ],
  }

**Comment by dhollinger** [comment]
I don't have official support for direct maps.

Definitely something I'm going to look into in the next few days. I'll update the issue when I have more info

**Comment by dhollinger** [comment]
Direct maps do require the directory to exist before mounting, so I will be adding support for nested mount points in the next release.

It maybe a few weeks, feel free to submit a pull request to add direct map support if you'd like to as well

**Comment by roweryan** [comment]
I'd like to see direct maps support too :+1: 

None of the other modules does it.

**Comment by dhollinger** [comment]
@roweryan @sknolin From what I'm reading in the autofs docs (want to make sure I'm not missing anything), I already support direct maps as per the basic definition.

However, currently the module doesn't support using the reserved "/-" autofs argument. Red Hat doesn't have any documentation on how to use this and CentOS/OEL has minimal docs on how to use it. Does anyone have a sample config file showing how you are using it? 

My guess is that there is a reason most autofs modules aren't supporting this option - it may not be used widely enough to support (or even know about).

That said, I will be testing the removal of the dependency on the
`file { $mount:
      ensure  => directory,
      require => Package[ 'autofs' ],
    }`
resource as autofs will create the directory if it is missing.

**Comment by sknolin** [comment]
We use it like this for example, for a cifs mount:

# /etc/auto.master contains

/- /etc/auto.foo --timeout=1200

# /etc/auto.foo contains

/foo -fstype=cifs,guest ://mybox.mydomain.com/data

**Comment by dhollinger** [comment]
Ah, ok that makes sense.

In that case, I shouldn't need to change any code with the generation of the auto.master and map files. I'll test this to be sure, along with removing the requirement for the mount folder to be there. I'm a bit busy this weekend, but I'll see what I can cook up by the end of next week.

**Comment by dhollinger** [comment]
Features added and tested.
